#!/bin/bash
#
# $Id: clean-files,v 1.3 2009/07/23 03:51:56 russoz Exp $
#
# Alexei Znamensky <russoz@user.sf.net>
#
# Feel free to send suggestions, comments. Flames go to /dev/null.
#

d=${0%/*}
here=$(echo $d | grep -qv ^/ && d=$( cd $(pwd)/${d}; pwd ); echo $d)
echo "here=$here" >&2

cd ${here}/../..

echo "Removing edit backups..."
find nb/ -name *~ -print | xargs -r rm

