#!/usr/bin/env bash
#
# $Id: configure-profile,v 1.3 2009/08/06 08:00:53 russoz Exp $
#
# Alexei Znamensky <russoz@user.sf.net>
#
# Feel free to send suggestions, comments. Flames go to /dev/null.
#

msg() {
  echo "$@" >&2
}

normalize_dir() {
  perl -MCwd=abs_path -le 'print abs_path(shift)' "$@"
}

##############################################################################

nbhome_dir="$1"
profile="$2"
force="${3:-0}"

[[ -z "$nbhome_dir" || -z "$profile" ]] && {
  msg "usage: ${0##*/} <NB home dir> <profile path> [<force>]";
  exit 1
}

[[ -w "${profile}" ]] || {
  msg "${0##*/}: Must have write permission on file ${profile}"
  exit 1
}

nbhome_dir=$(normalize_dir ${nbhome_dir})

msg "Configuring NB into the user profile"
if grep -q nb/load "${profile}"; then
  if [[ "$force" -eq "1" ]]; then
    perl -i.bak -pe \
      "\$_ = \". ${nbhome_dir%/}/load\" if |nb/load|" ${profile} || {
        msg "*** ${0##*/}: Failed to replace the existing configuration"
        exit 1
    }
  else
    msg "  Already found a NB install on \"${profile}\"."
    msg "  Not touching the file."
  fi
else
  [[ -f "${profile}" ]] && cp ${profile} ${profile}.bak
  msg "${0##*/}: Installing NB on ${profile}"
  ( echo ""; echo ". ${nbhome_dir%/}/load" ) >> "${profile}"
fi

# Emacs config
#
# Local Variables:
# tab-width 2
# sh-basic-offset 2
# End:

