#!/usr/bin/env bash
#
# Alexei Znamensky <russoz@user.sf.net>
#
# Feel free to send suggestions, comments. Flames go to /dev/null.
#

nb_src="$1"
nb_dst="$2"

dir=${0%/*}

${dir}/copy-nb ${nb_src} ${nb_dst} && {
  ${dir}/configure-profile ${nb_dst} ${HOME}/.bashrc \
    || ${dir}/configure-profile ${nb_dst} ${HOME}/.profile
}

# Emacs config
#
# Local Variables:
# tab-width 2
# sh-basic-offset 2
# End:

