#!/bin/bash
#
# $Id: show-diff,v 1.3 2009/07/23 03:51:56 russoz Exp $
#
# Alexei Znamensky <russoz@user.sf.net>
#
# Feel free to send suggestions, comments. Flames go to /dev/null.
#

usage() {
	echo "usage: show-diff <old-tag> <new-tag>" >&2
}
r1="$1"
r2="$2"

[ -z "$r1" ] && usage && exit 1
[ -z "$r2" ] && usage && exit 1

CVSROOT=":extssh:russoz@nicebashing.cvs.sf.net:/cvsroot/nicebashing"
export CVSROOT

d=${0%/*}
here=$(echo $d | grep -qv ^/ && d=$( cd $(pwd)/${d}; pwd ); echo $d)
echo "here=$here" >&2

cd ${here}/../..

cvs -q patch -r "$r1" -r "$r2" . 
