#!/bin/bash
#
# $Id: upload-to-sf,v 1.2 2009/07/23 03:51:56 russoz Exp $
#
# Alexei Znamensky <russoz@user.sf.net>
#
# Feel free to send suggestions, comments. Flames go to /dev/null.
#

usage() {
	echo "usage: upload-to-sf <filename>" >&2
}

upload_dir="frs.sf.net:uploads/"

file="$1"
[ -z "$file" ] && usage && exit 1

rsync -vPC $file $upload_dir/${file##*/}

