#!/bin/sh -e 'echo Do not run this >&2; exit 1'
#
# $Id: nb-ctl,v 1.3 2009/08/06 07:24:03 russoz Exp $
#
# Alexei Znamensky <russoz@users.sf.net> 
#
# Feel free to send suggestions, comments. Flames go to /dev/null.
#

[[ -n "${_NB_CTL}" ]] && return
_NB_CTL='$Id: nb-ctl,v 1.3 2009/08/06 07:24:03 russoz Exp $'
nb_vecho $_NB_CTL

##
#
# Template functions to control the components of an IBM WebSphere Application
# Server, namely an App Server, a Node Agent, a Deployment Mgr and an
# IBM HTTP Server (IHS).
#

usage_wasctl() {
	echo "usage: _wasctl <service-name> <was-root> <server> <command> [<user> <password>]" >&2
}

#
# _wasctl <service-name> <was-root> <server> <command> [<user> <password>]
#
_wasctl() {
	N="$1"
	R="$2"
	S="$3"
	C="$4"
	U="$5"
	P="$6"

	[[ -z "$N" ]] && usage_wasctl && return 1
	[[ -z "$R" ]] && usage_wasctl && return 1
	[[ -z "$S" ]] && usage_wasctl && return 1

	UP=""
	if [[ -n "$U" ]]; then
		[[ -z "$P" ]] && usage_wasctl && return 1

		UP="-username ${U} -password ${P}"
	fi

	echo ""
	echo "------------------- wasctl: ${N}(${S}) CMD=${C}"

	case "$C" in
		start)
			${R}/bin/startServer.sh ${S} ${UP}
		;;

		stop)
			${R}/bin/stopServer.sh ${S} ${UP}
		;;

		status)
			${R}/bin/serverStatus.sh ${S} ${UP}
		;;

		status-all)
			${R}/bin/serverStatus.sh all ${UP}
		;;

		restart)
			$0 stop
			$0 start
		;;

		*)
			echo "usage: $N (start|stop|restart|status|status-all)" >&2
			return 1
		;;
	esac

	return 0
}

usage_wasnodectl() {
	echo "usage: _wasnodectl <service-name> <was-root> <command> [<user> <password>]" >&2
}

#
# _wasnodectl <service-name> <was-root> <command> [<user> <password>]
#
_wasnodectl() {
	N="$1"
	R="$2"
	C="$3"
	U="$4"
	P="$5"

	[[ -z "$N" ]] && usage_wasnodectl && return 1
	[[ -z "$R" ]] && usage_wasnodectl && return 1

	UP=""
	if [[ -n "$U" ]]; then
		[[ -z "$P" ]] && usage_wasnodectl && return 1

		UP="-username ${U} -password ${P}"
	fi

	echo ""
	echo "------------------- wasnodectl: ${N} CMD=${C}"

	case "$C" in
		start)
			${R}/bin/startNode.sh ${UP}
		;;

		stop)
			${R}/bin/stopNode.sh ${S} ${UP}
		;;

		status)
			${R}/bin/serverStatus.sh nodeagent ${UP}
		;;

		status-all)
			${R}/bin/serverStatus.sh all ${UP}
		;;

		restart)
			$0 stop
			$0 start
		;;

		*)
			echo "usage: $N (start|stop|restart|status|status-all)" >&2
			return 1
		;;
	esac

	return 0
}

usage_wasdmgrctl() {
	echo "usage: _wasdmgrctl <service-name> <was-root> <command> [<user> <password>]" >&2
}

#
# _wasdmgrctl <service-name> <was-root> <command> [<user> <password>]
#
_wasdmgrctl() {
	N="$1"
	R="$2"
	C="$3"
	U="$4"
	P="$5"

	[[ -z "$N" ]] && usage_wasdmgrctl && return 1
	[[ -z "$R" ]] && usage_wasdmgrctl && return 1

	UP=""
	if [[ -n "$U" ]]; then
		[[ -z "$P" ]] && usage_wasdmgrctl && return 1

		UP="-username ${U} -password ${P}"
	fi

	echo ""
	echo "------------------- wasdmgrctl: ${N} CMD=${C}"

	case "$C" in
		start)
			${R}/bin/startManager.sh ${UP}
		;;

		stop)
			${R}/bin/stopManager.sh ${S} ${UP}
		;;

		status)
			${R}/bin/serverStatus.sh dmgr ${UP}
		;;

		status-all)
			${R}/bin/serverStatus.sh all ${UP}
		;;

		restart)
			$0 stop
			$0 start
		;;

		*)
			echo "usage: $N (start|stop|restart|status|status-all)" >&2
			return 1
		;;
	esac

	return 0
}

usage_ihsctl() {
	echo "usage: _ihsctl <service-name> <ihs-root> <command>" >&2
}

#
# _ihsctl <service-name> <ihs-root> <command>
#
_ihsctl() {
	N="$1"
	R="$2"
	C="$3"

	[[ -z "$N" ]] && usage_ihsctl && return 1
	[[ -z "$R" ]] && usage_ihsctl && return 1

	echo ""
	echo "------------------- ihsctl: ${N} CMD=${C}"

	case "$C" in
		start)
			${R}/bin/apachectl start
		;;

		stop)
			${R}/bin/apachectl stop
		;;

		graceful)
			${R}/bin/apachectl graceful
		;;

		status)
			${R}/bin/apachectl status
		;;

		restart)
			$0 stop
			$0 start
		;;

		*)
			echo "usage: $N (start|stop|graceful|restart|status)" >&2
			return 1
		;;
	esac

	return 0
}

usage_ldapctl() {
  echo "usage: _ldapctl <service-name> <ldap-bin> <instance> <command>" >&2
}

#
# _ldapctl <service-name> <ldap-bin> <instance> <command>
#
_ldapctl() {
	N="$1"
	R="$2"
	I="$3"
	C="$4"

	[[ -z "$N" ]] && usage_wasctl && return 1
	[[ -z "$R" ]] && usage_wasctl && return 1
	[[ -z "$I" ]] && usage_wasctl && return 1
	[[ -z "$C" ]] && usage_wasctl && return 1

	echo ""
	echo "------------------- ldapctl: ${N}(${I}) CMD=${C}"

	case "$C" in
		start)
			${R}/ibmslapd -I ${I}
		;;

		stop)
			${R}/ibmslapd -I ${I} -k 
		;;

		status)
			ps -ef | grep slapd | grep -v grep
		;;

		restart)
			$0 stop
			$0 start
		;;

		*)
			echo "usage: $N (start|stop|restart|status)" >&2
			return 1
		;;
	esac

	return 0
}

# Emacs config
#
# Local Variables:
# tab-width 2
# sh-basic-offset 2
# End:

