#!/bin/bash -e 'echo Do not run this >&2; exit 1'
#
# Alexei Znamensky <russoz@users.sf.net> 
#
# Feel free to send suggestions, comments. Flames go to /dev/null.
#

[[ -n "${_NB_REMOTE}" ]] && return
_NB_REMOTE=1

# functions here

remote-nb() {
  local SERVER="$1"; shift
  ssh ${SERVER} '. ${HOME}/.nb/load; '"${@}"
}

remote-fetch-files() {
	local SERVER="$1"
	local REMDIR="$2"
	local FILES="$3"

	scp -prC "${SERVER}:${REMDIR}/${FILES}" .
}

remote-tail-file() {
	local SERVER="$1"
	local REMDIR="$2"
	local FILE="$3"
	
	ssh ${SERVER} "tail -f ${REMDIR}/${FILE}"
}


#############################################################################

# aliases and one-time runs here

# Emacs config
#
# Local Variables:
# tab-width 2
# sh-basic-offset 2
# End:
