#!/bin/sh -e 'echo Do not run this >&2; exit 1'
#
# $Id: defaults,v 1.1 2008/09/23 07:46:17 russoz Exp $
#
# Alexei Znamensky <russoz@users.sf.net>
#
# Feel free to send suggestions, comments. Flames go to /dev/null.
#

# Module options

#skel_set_option 1
#skel_closet_path /home/old/stories

