#!/bin/sh -e 'echo Do not run this >&2; exit 1'
#
# Alexei Znamensky <russoz@users.sf.net> 
#
# Feel free to send suggestions, comments. Flames go to /dev/null.
#

[ -n "${_NB_SKEL}" ] && return
_NB_SKEL=1

#nb_depends nb-somemodule nb-someothermodule || return 1

# functions here

#############################################################################

# aliases and one-time runs here

# Emacs config
#
# Local Variables:
# tab-width 2
# sh-basic-offset 2
# End:
