#!/bin/bash
#
# Alexei Znamensky <russoz@cpan.org>
#
# Feel free to send suggestions, comments.
#

usage() {
	echo "usage: upload-to-sf <filename>" >&2
}

upload_dir="frs.sf.net:uploads/"

file="$1"
[ -z "$file" ] && usage && exit 1

rsync -vPC $file $upload_dir/${file##*/}

