#!/bin/bash -e 'echo Do not run this >&2; exit 1'
#
# Alexei Znamensky <russoz@users.sf.net> 
#
# Feel free to send suggestions, comments. Flames go to /dev/null.
#

[[ -n "${_NB_NET}" ]] && return
_NB_NET='$Id: nb-net,v 1.4 2009/10/11 12:24:14 russoz Exp $'
nb_vecho $_NB_NET

# functions here
net-show-listen() {
  netstat -a "$@" | grep LISTEN | grep -v ^unix
}


#############################################################################

# aliases and one-time runs here

# Emacs config
#
# Local Variables:
# tab-width 2
# sh-basic-offset 2
# End:
