#!/bin/bash -e 'echo Do not run this >&2; exit 1'
#
# Alexei Znamensky <russoz@cpan.org>
#
# Feel free to send suggestions, comments.
#

# aliases and one-time runs here
wrap-bin ${NB_HOME}/bin/prop-*

# Emacs config
#
# Local Variables:
# tab-width 2
# sh-basic-offset 2
# End:
